### PR TITLE
Google prompt parameter

### PR DESCRIPTION
**Pull request by 3da**
Hello.

I need parameter "prompt" for Google OAauth2

Thanks.

### CODE REVIEW

**Comment by Tratcher** [comment]
It looks like this used to be called approval_prompt.
https://github.com/google/oauth2client/issues/453#issuecomment-195379235
There was support for setting this on a per-challenge basis.
https://github.com/aspnet/AspNetKatana/blob/8cda3619132b7d1c31392ccc38ef4bb6bac92a89/src/Microsoft.Owin.Security.Google/GoogleOAuth2AuthenticationHandler.cs#L197
Compare to the latest version:
https://github.com/aspnet/Security/blob/305ccf9cc5d2ce777e5fb147013966924c9aca8e/src/Microsoft.AspNetCore.Authentication.Google/GoogleHandler.cs#L63-L68
If you just want to update that list of query params quick then I think we can take it. I don't think adding Prompt directly to Options would be as useful.

**Comment by 3da** [comment]
As it written here https://github.com/google/oauth2client/issues/453#issuecomment-195379235
I need prompt=consent
So how can I do it without adding new parameter to Options?

**Comment by Tratcher** [comment]
Additional query params can be specified in the AuthenticationProperties in the call to Challenge. But we'll need to add `Prompt` to that list of parameters here: https://github.com/aspnet/AspNetKatana/blob/8cda3619132b7d1c31392ccc38ef4bb6bac92a89/src/Microsoft.Owin.Security.Google/GoogleOAuth2AuthenticationHandler.cs#L197

**Comment by 3da** [comment]
I am not abosulte expert so I don't know how it will be better. But I want to have ability to change this property in future versions of this library.

Thanks.

**Comment by Tratcher** [comment]
Resolved via https://github.com/aspnet/AspNetKatana/pull/44/commits/27a5a00924f4ff5a26eff6e751570d8b280d5769

**Comment by 3da** [comment]
Thanks

**Pull request closed without merging**
